language: bash
sudo: false
addons:
  apt:
    packages:
    - shellcheck
before_script:
 - chmod +x ./build.sh
 - chmod +x ./clean-docker-images.sh
script:
  - ./build.sh
notifications:
  email: false
