language: bash
sudo: required
before_install:
  - wget http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.3.7-1_amd64.deb
  - sudo dpkg -i shellcheck_0.3.7-1_amd64.deb
script:
  - ./build.sh
notifications:
  email: false
